version: 0.2

phases:
  install:
    commands:
      - sudo yum install -y wget tar

  build:
    commands:
      - wget https://github.com/filebrowser/filebrowser/releases/download/v2.32.0/linux-amd64-filebrowser.tar.gz
      - tar -xvf linux-amd64-filebrowser.tar.gz

  post_build:
    commands:
      - echo "completed"
      - chmod 777 scripts/*
      
artifacts:
  files:
    - **/**
